version: '3.8'

services:
  app:
    build: .
    container_name: helpdesk_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - helpdesk_network

  web:
    image: nginx:latest
    container_name: helpdesk_web
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - helpdesk_network

  db:
    image: mysql:8
    container_name: helpdesk_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: helpdesk
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - helpdesk_network

  redis:
    image: redis:alpine
    container_name: helpdesk_redis
    restart: always
    networks:
      - helpdesk_network

networks:
  helpdesk_network:

volumes:
  db_data:
